package report

import (
	"fmt"
	"html"
	"io"
	"sort"
	"strings"
	"time"

	"github.com/metalstormbass/snyft/pkg/models"
)

func (r *Reporter) generateHTML() error {
	w := r.config.Writer

	// Sort results by risk: HIGH first, then MEDIUM, then LOW
	sorted := make([]models.AnalysisResult, len(r.results))
	copy(sorted, r.results)
	sort.SliceStable(sorted, func(i, j int) bool {
		return riskOrdinal(sorted[i].RiskLevel) > riskOrdinal(sorted[j].RiskLevel)
	})

	if _, err := fmt.Fprint(w, `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Snyft Supply Chain Risk Report</title>
<style>
`); err != nil {
		return err
	}
	r.printHTMLStyles(w)
	if _, err := fmt.Fprint(w, `</style>
</head>
<body>
<div class="wrap">
`); err != nil {
		return err
	}

	r.printHTMLHeader(w)
	if err := r.printHTMLExecutiveSummary(w); err != nil {
		return err
	}
	r.printHTMLTopFindings(w)
	r.printHTMLRiskAreas(w)

	// Detailed findings
	f(w, "<section class=\"section\">\n")
	f(w, "<h2 class=\"section-title\">Package Details</h2>\n")
	f(w, "<p class=\"section-desc\">Click a package to expand its full analysis. Sorted by risk score, highest first.</p>\n")
	for i, result := range sorted {
		r.printHTMLPackage(w, result, i)
	}
	f(w, "</section>\n")

	// Footer
	f(w, "<footer class=\"footer\">Generated by <strong>Snyft</strong> &mdash; Supply Chain Risk Assessment &mdash; %s</footer>\n",
		time.Now().Format("2006-01-02 15:04:05"))

	f(w, "</div>\n")
	r.printHTMLScript(w)
	f(w, "</body>\n</html>\n")
	return nil
}

func riskOrdinal(level string) int {
	switch level {
	case "HIGH":
		return 3
	case "MEDIUM":
		return 2
	case "LOW":
		return 1
	default:
		return 0
	}
}

// packageSlug generates an HTML-safe ID from a package name.
// Non-alphanumeric characters are replaced with hyphens and leading/trailing
// hyphens are removed.
func packageSlug(name string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(name) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		} else {
			b.WriteByte('-')
		}
	}
	return strings.Trim(b.String(), "-")
}

func (r *Reporter) printHTMLHeader(w io.Writer) {
	f(w, `<header class="header">
<div class="header-inner">
<div class="logo">
<svg width="32" height="32" viewBox="0 0 32 32" fill="none"><circle cx="16" cy="16" r="15" stroke="#52b788" stroke-width="2"/><path d="M10 17l4 4 8-10" stroke="#52b788" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/></svg>
<div>
<h1 class="logo-text">Snyft</h1>
<span class="logo-sub">Supply Chain Risk Report</span>
</div>
</div>
<div class="header-meta">
<span class="header-date">%s</span>
</div>
</div>
</header>
`, time.Now().Format("Jan 2, 2006 at 15:04"))
}

func (r *Reporter) printHTMLStyles(w io.Writer) {
	f(w, `*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif;line-height:1.6;color:#e0e0e0;background:#0a0a0a;font-size:14px;-webkit-font-smoothing:antialiased}
.wrap{max-width:1000px;margin:0 auto;padding:24px 16px}
@media(min-width:768px){.wrap{padding:32px 24px}}

/* Header */
.header{margin-bottom:32px}
.header-inner{display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:12px}
.logo{display:flex;align-items:center;gap:12px}
.logo-text{font-size:24px;font-weight:700;color:#52b788;line-height:1.2}
.logo-sub{font-size:13px;color:#808080;font-weight:400}
.header-meta{font-size:13px;color:#808080}

/* Cards */
.dashboard{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:16px;margin-bottom:32px}
.stat-card{background:#1a1a1a;border-radius:12px;padding:20px;box-shadow:0 1px 3px rgba(0,0,0,0.3),0 1px 2px rgba(0,0,0,0.2);border:1px solid #1b4332;position:relative;overflow:hidden}
.stat-card::before{content:'';position:absolute;top:0;left:0;right:0;height:3px}
.stat-card.risk-high::before{background:#ef4444}
.stat-card.risk-med::before{background:#f59e0b}
.stat-card.risk-low::before{background:#52b788}
.stat-card.risk-info::before{background:#40916c}
.stat-label{font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.05em;color:#808080;margin-bottom:8px}
.stat-value{font-size:28px;font-weight:700;line-height:1}
.stat-value.high{color:#ef4444}
.stat-value.medium{color:#f59e0b}
.stat-value.low{color:#52b788}
.stat-sub{font-size:12px;color:#666666;margin-top:6px}
.stat-breakdown{display:flex;gap:12px;margin-top:8px;font-size:12px;font-weight:500}
.stat-breakdown .high{color:#ef4444}
.stat-breakdown .med{color:#d97706}
.stat-breakdown .low{color:#52b788}

/* Risk meter */
.risk-meter{height:6px;background:#1b4332;border-radius:3px;margin-top:12px;overflow:hidden;display:flex}
.risk-meter span{height:100%%}
.risk-meter .seg-high{background:#ef4444}
.risk-meter .seg-med{background:#f59e0b}
.risk-meter .seg-low{background:#52b788}

/* Package links in summary */

/* Sections */
.section{background:#1a1a1a;border-radius:12px;padding:24px;margin-bottom:24px;box-shadow:0 1px 3px rgba(0,0,0,0.3),0 1px 2px rgba(0,0,0,0.2);border:1px solid #1b4332}
.section-title{font-size:16px;font-weight:700;color:#40916c;margin-bottom:4px}
.section-desc{font-size:13px;color:#808080;margin-bottom:16px}

/* Top findings */
.top-finding{display:flex;align-items:flex-start;gap:12px;padding:12px 16px;border-radius:8px;margin-bottom:8px;border:1px solid #1b4332;background:#222222;transition:background 0.15s}
.top-finding:hover{background:#2a2a2a}
.top-finding-num{font-size:12px;font-weight:700;color:#666666;min-width:20px;padding-top:2px}
.top-finding-body{flex:1;min-width:0}
.top-finding-pkg{font-weight:600;color:#e0e0e0;font-size:14px}
a.top-finding-pkg{text-decoration:none}
a.top-finding-pkg:hover{text-decoration:underline;color:#52b788}
.top-finding-eco{font-size:11px;color:#666666;font-weight:400;margin-left:6px}
.top-finding-desc{font-size:13px;color:#b0b0b0;margin-top:2px}
.sev-badge{display:inline-block;padding:1px 8px;border-radius:10px;font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:0.03em;vertical-align:middle}
.sev-badge.critical,.sev-badge.high{background:#3a1111;color:#ef4444;border:1px solid #5c2020}
.sev-badge.medium{background:#3a2a0a;color:#f59e0b;border:1px solid #5c4510}
.sev-badge.low{background:#0d2818;color:#52b788;border:1px solid #1b4332}

/* Risk areas */
.risk-area{padding:14px 16px;border-radius:8px;margin-bottom:10px;border-left:3px solid #1b4332;background:#222222}
.risk-area.area-high{border-left-color:#ef4444;background:#1f1010}
.risk-area.area-med{border-left-color:#f59e0b;background:#1f1a0a}
.risk-area.area-low{border-left-color:#52b788;background:#0d2818}
.risk-area-tag{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.04em;margin-bottom:4px}
.risk-area.area-high .risk-area-tag{color:#ef4444}
.risk-area.area-med .risk-area-tag{color:#f59e0b}
.risk-area.area-low .risk-area-tag{color:#52b788}
.risk-area-summary{font-size:14px;font-weight:600;color:#e0e0e0;margin-bottom:2px}
.risk-area-explain{font-size:13px;color:#808080}
.risk-area-examples{font-size:12px;color:#666666;margin-top:4px}
.risk-area-examples a{color:#74c69d;text-decoration:none}
.risk-area-examples a:hover{text-decoration:underline;color:#52b788}

/* Package cards */
.pkg-card{border:1px solid #1b4332;border-radius:10px;margin-bottom:12px;overflow:hidden;background:#1a1a1a;transition:box-shadow 0.15s}
.pkg-card:hover{box-shadow:0 2px 8px rgba(0,0,0,0.3)}
.pkg-card.high{border-left:4px solid #ef4444}
.pkg-card.medium{border-left:4px solid #f59e0b}
.pkg-card.low{border-left:4px solid #52b788}
.pkg-header{display:flex;align-items:center;justify-content:space-between;padding:14px 18px;cursor:pointer;user-select:none;-webkit-user-select:none;gap:12px}
.pkg-header:hover{background:#252525}
.pkg-left{display:flex;align-items:center;gap:12px;min-width:0;flex:1}
.pkg-name{font-size:15px;font-weight:600;color:#e0e0e0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.pkg-trans{font-size:11px;color:#666666;font-weight:400}
.pkg-right{display:flex;align-items:center;gap:10px;flex-shrink:0}
.pkg-score{font-size:13px;font-weight:600;color:#808080}
.risk-badge{display:inline-flex;align-items:center;padding:3px 10px;border-radius:6px;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.04em}
.risk-badge.high{background:#3a1111;color:#ef4444;border:1px solid #5c2020}
.risk-badge.medium{background:#3a2a0a;color:#f59e0b;border:1px solid #5c4510}
.risk-badge.low{background:#0d2818;color:#52b788;border:1px solid #1b4332}
.chevron{width:20px;height:20px;color:#666666;transition:transform 0.2s;flex-shrink:0}
.pkg-card.open .chevron{transform:rotate(180deg)}
.pkg-body{display:none;padding:0 18px 18px;border-top:1px solid #1b4332}
.pkg-card.open .pkg-body{display:block}

/* Metadata row */
.pkg-meta{display:flex;flex-wrap:wrap;gap:6px 18px;font-size:13px;color:#808080;padding:12px 0;border-bottom:1px solid #1b4332;margin-bottom:14px}
.pkg-meta a{color:#52b788;text-decoration:none}
.pkg-meta a:hover{text-decoration:underline}
.meta-label{font-weight:600;color:#b0b0b0}

/* Category scores grid */
.cat-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:8px;margin-bottom:16px}
.cat-item{display:flex;align-items:center;gap:8px;padding:8px 12px;border-radius:8px;background:#222222;border:1px solid #1b4332;font-size:13px}
.cat-item.risk-2{background:#1f1010;border-color:#5c2020}
.cat-item.risk-1{background:#1f1a0a;border-color:#5c4510}
.cat-item.risk-0{background:#0d2818;border-color:#1b4332}
.cat-item.skipped{opacity:0.45}
.cat-dot{width:8px;height:8px;border-radius:50%%;flex-shrink:0}
.cat-dot.dot-0{background:#52b788}
.cat-dot.dot-1{background:#f59e0b}
.cat-dot.dot-2{background:#ef4444}
.cat-dot.dot-skip{background:#444444}
.cat-name{flex:1;color:#c0c0c0;font-weight:500}
.cat-score{font-weight:700;color:#b0b0b0;font-size:12px}
.cat-verified{font-size:11px;color:#666666}

/* Findings */
.findings-title{font-size:13px;font-weight:700;color:#b0b0b0;text-transform:uppercase;letter-spacing:0.04em;margin-bottom:10px}
.finding-item{padding:10px 14px;border-radius:8px;margin-bottom:6px;font-size:13px;border:1px solid #1b4332;background:#222222}
.finding-item.f-high,.finding-item.f-critical{border-color:#5c2020;background:#1f1010}
.finding-item.f-medium{border-color:#5c4510;background:#1f1a0a}
.finding-item.f-low{border-color:#1b4332;background:#0d2818}
.finding-desc{color:#c0c0c0;margin-top:4px}
.finding-extra{font-size:12px;color:#666666;margin-top:4px}
.finding-extra a{color:#52b788;text-decoration:none}
.finding-extra a:hover{text-decoration:underline}

/* Success */
.success-msg{display:flex;align-items:center;gap:8px;padding:14px 18px;border-radius:8px;background:#0d2818;border:1px solid #1b4332;color:#52b788;font-weight:600;font-size:14px}

/* Footer */
.footer{text-align:center;font-size:12px;color:#666666;padding:24px 0 8px;margin-top:8px}
.footer strong{color:#52b788;font-weight:600}

/* Responsive */
@media(max-width:640px){
.dashboard{grid-template-columns:1fr 1fr}
.stat-value{font-size:22px}
.pkg-header{padding:12px 14px}
.pkg-body{padding:0 14px 14px}
.cat-grid{grid-template-columns:1fr}
.header-inner{flex-direction:column;align-items:flex-start}
}
@media(max-width:400px){
.dashboard{grid-template-columns:1fr}
}

/* Print */
@media print{
body{background:#fff;color:#1e293b}
.wrap{padding:0}
.pkg-card .pkg-body{display:block!important}
.chevron{display:none}
.section,.stat-card,.pkg-card{box-shadow:none;break-inside:avoid}
}
`)
}

func (r *Reporter) printHTMLExecutiveSummary(w io.Writer) error {
	overall := calculateOverallRisk(r.stats)
	duration := r.stats.EndTime.Sub(r.stats.StartTime)

	overallCls := "low"
	switch overall {
	case "HIGH":
		overallCls = "high"
	case "MEDIUM":
		overallCls = "medium"
	}

	f(w, "<div class=\"dashboard\">\n")

	// Overall risk card
	riskCardClass := "risk-high"
	switch overall {
	case "MEDIUM":
		riskCardClass = "risk-med"
	case "LOW":
		riskCardClass = "risk-low"
	}
	f(w, "<div class=\"stat-card %s\">\n", riskCardClass)
	f(w, "<div class=\"stat-label\">Overall Risk</div>\n")
	f(w, "<div class=\"stat-value %s\">%s</div>\n", overallCls, overall)
	f(w, "</div>\n")

	// Packages card
	f(w, "<div class=\"stat-card risk-info\">\n")
	f(w, "<div class=\"stat-label\">Packages Analyzed</div>\n")
	f(w, "<div class=\"stat-value\">%d</div>\n", r.stats.TotalPackages)
	if r.stats.TotalPackages > 0 {
		f(w, "<div class=\"stat-breakdown\"><span class=\"high\">%d high</span><span class=\"med\">%d med</span><span class=\"low\">%d low</span></div>\n",
			r.stats.HighRisk, r.stats.MediumRisk, r.stats.LowRisk)
		// Risk meter bar
		total := float64(r.stats.TotalPackages)
		if total > 0 {
			f(w, "<div class=\"risk-meter\">")
			if r.stats.HighRisk > 0 {
				f(w, "<span class=\"seg-high\" style=\"width:%.1f%%\"></span>", float64(r.stats.HighRisk)/total*100)
			}
			if r.stats.MediumRisk > 0 {
				f(w, "<span class=\"seg-med\" style=\"width:%.1f%%\"></span>", float64(r.stats.MediumRisk)/total*100)
			}
			if r.stats.LowRisk > 0 {
				f(w, "<span class=\"seg-low\" style=\"width:%.1f%%\"></span>", float64(r.stats.LowRisk)/total*100)
			}
			f(w, "</div>\n")
		}
	}
	f(w, "</div>\n")

	// Dependencies card
	if r.stats.DirectDeps > 0 || r.stats.TransitiveDeps > 0 {
		f(w, "<div class=\"stat-card risk-info\">\n")
		f(w, "<div class=\"stat-label\">Dependencies</div>\n")
		f(w, "<div class=\"stat-value\">%d</div>\n", r.stats.DirectDeps+r.stats.TransitiveDeps)
		f(w, "<div class=\"stat-sub\">%d direct &middot; %d transitive</div>\n", r.stats.DirectDeps, r.stats.TransitiveDeps)
		f(w, "</div>\n")
	}

	// Duration card
	f(w, "<div class=\"stat-card risk-info\">\n")
	f(w, "<div class=\"stat-label\">Scan Duration</div>\n")
	f(w, "<div class=\"stat-value\" style=\"font-size:22px\">%s</div>\n", html.EscapeString(formatDuration(duration)))
	f(w, "</div>\n")

	f(w, "</div>\n")
	return nil
}

func (r *Reporter) printHTMLTopFindings(w io.Writer) {
	criticalIssues := r.extractCriticalIssues(5)
	if len(criticalIssues) == 0 {
		return
	}

	f(w, "<section class=\"section\">\n")
	f(w, "<h2 class=\"section-title\">Top Priority Findings</h2>\n")
	f(w, "<p class=\"section-desc\">Most critical supply chain risk signals across all packages.</p>\n")

	for i, issue := range criticalIssues {
		sevCls := "medium"
		if issue.Severity == "HIGH" || issue.Severity == "CRITICAL" {
			sevCls = "high"
		}
		slug := packageSlug(issue.PackageName)
		f(w, "<div class=\"top-finding\">\n")
		f(w, "<div class=\"top-finding-num\">%d</div>\n", i+1)
		f(w, "<div class=\"top-finding-body\">\n")
		f(w, "<div><a href=\"#pkg-%s\" class=\"top-finding-pkg\" onclick=\"showPkg('%s')\">%s@%s</a><span class=\"top-finding-eco\">%s</span> <span class=\"sev-badge %s\">%s</span></div>\n",
			slug,
			slug,
			html.EscapeString(issue.PackageName),
			html.EscapeString(issue.PackageVersion),
			html.EscapeString(issue.Ecosystem),
			sevCls,
			html.EscapeString(issue.Severity))
		f(w, "<div class=\"top-finding-desc\">%s</div>\n", html.EscapeString(issue.Description))
		if issue.SourceURL != "" {
			f(w, "<div class=\"finding-extra\">Source: <a href=\"%s\" target=\"_blank\" rel=\"noopener\">%s</a></div>\n",
				html.EscapeString(issue.SourceURL), html.EscapeString(issue.SourceURL))
		}
		f(w, "</div>\n")
		f(w, "</div>\n")
	}

	f(w, "</section>\n")
}

func (r *Reporter) printHTMLRiskAreas(w io.Writer) {
	areas := r.generateRiskAreas()

	f(w, "<section class=\"section\">\n")
	f(w, "<h2 class=\"section-title\">Key Risk Areas</h2>\n")
	f(w, "<p class=\"section-desc\">Cross-cutting supply chain risk patterns across all analyzed packages.</p>\n")

	if len(areas) == 0 {
		f(w, "<div class=\"success-msg\">&#10003; No critical supply chain risk factors identified.</div>\n")
	} else {
		for _, area := range areas {
			var areaCls string
			switch area.Tag {
			case "HIGH RISK":
				areaCls = "area-high"
			default:
				areaCls = "area-med"
			}
			f(w, "<div class=\"risk-area %s\">\n", areaCls)
			f(w, "<div class=\"risk-area-tag\">%s</div>\n", html.EscapeString(area.Tag))
			f(w, "<div class=\"risk-area-summary\">%s</div>\n", html.EscapeString(area.Summary))
			f(w, "<div class=\"risk-area-explain\">%s</div>\n", html.EscapeString(area.Explanation))
			if len(area.Examples) > 0 {
				f(w, "<div class=\"risk-area-examples\">Affected: ")
				for i, name := range area.Examples {
					if i > 0 {
						f(w, ", ")
					}
					slug := packageSlug(name)
					f(w, "<a href=\"#pkg-%s\">%s</a>", slug, html.EscapeString(name))
				}
				f(w, "</div>\n")
			}
			f(w, "</div>\n")
		}
	}

	f(w, "</section>\n")
}

func (r *Reporter) printHTMLPackage(w io.Writer, result models.AnalysisResult, index int) {
	cls := "low"
	switch result.RiskLevel {
	case "HIGH":
		cls = "high"
	case "MEDIUM":
		cls = "medium"
	}

	// First 3 HIGH risk packages start expanded
	openCls := ""
	if result.RiskLevel == "HIGH" && index < 3 {
		openCls = " open"
	}

	slug := packageSlug(result.Dependency.Name)
	f(w, "<div class=\"pkg-card %s%s\" id=\"pkg-%s\">\n", cls, openCls, slug)

	// Clickable header
	f(w, "<div class=\"pkg-header\" onclick=\"toggle('%s')\">\n", slug)
	f(w, "<div class=\"pkg-left\">\n")
	name := html.EscapeString(result.Dependency.Name) + "@" + html.EscapeString(result.Dependency.Version)
	f(w, "<span class=\"pkg-name\">%s</span>\n", name)
	if result.Dependency.IsTransitive {
		f(w, "<span class=\"pkg-trans\">transitive</span>\n")
	}
	f(w, "</div>\n")
	f(w, "<div class=\"pkg-right\">\n")
	if result.SupplyChainScore != nil {
		ms := maxScore(result.SupplyChainScore)
		f(w, "<span class=\"pkg-score\">%d/%d</span>\n", result.SupplyChainScore.TotalScore, ms)
	}
	f(w, "<span class=\"risk-badge %s\">%s</span>\n", cls, result.RiskLevel)
	f(w, "<svg class=\"chevron\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path fill-rule=\"evenodd\" d=\"M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z\" clip-rule=\"evenodd\"/></svg>\n")
	f(w, "</div>\n")
	f(w, "</div>\n")

	// Expandable body
	f(w, "<div class=\"pkg-body\">\n")

	// Metadata
	f(w, "<div class=\"pkg-meta\">\n")
	f(w, "<span><span class=\"meta-label\">Ecosystem:</span> %s</span>\n", html.EscapeString(string(result.Dependency.Ecosystem)))
	if result.RepositoryURL != "" {
		f(w, "<span><span class=\"meta-label\">Repo:</span> <a href=\"%s\" target=\"_blank\" rel=\"noopener\">%s</a></span>\n",
			html.EscapeString(result.RepositoryURL), html.EscapeString(result.RepositoryURL))
	}
	if result.SourceCodeAvailable {
		f(w, "<span><span class=\"meta-label\">Source:</span> Available</span>\n")
	} else {
		f(w, "<span><span class=\"meta-label\">Source:</span> Unavailable</span>\n")
	}
	f(w, "</div>\n")

	// Category scores (verbose mode or always if supply chain score exists)
	if result.SupplyChainScore != nil {
		f(w, "<div class=\"cat-grid\">\n")
		for _, cat := range categoryList(result.SupplyChainScore.CategoryScores) {
			if cat.Score.Skipped {
				f(w, "<div class=\"cat-item skipped\"><span class=\"cat-dot dot-skip\"></span><span class=\"cat-name\">%s</span><span class=\"cat-score\">SKIP</span></div>\n",
					html.EscapeString(cat.Name))
				continue
			}
			riskCls := fmt.Sprintf("risk-%d", cat.Score.RiskPoints)
			dotCls := fmt.Sprintf("dot-%d", cat.Score.RiskPoints)
			verified := ""
			if !cat.Score.Verified {
				verified = " <span class=\"cat-verified\">?</span>"
			}
			f(w, "<div class=\"cat-item %s\"><span class=\"cat-dot %s\"></span><span class=\"cat-name\">%s</span><span class=\"cat-score\">%d/2%s</span></div>\n",
				riskCls, dotCls, html.EscapeString(cat.Name), cat.Score.Score, verified)
		}
		f(w, "</div>\n")
	}

	// Findings
	if len(result.Findings) > 0 {
		f(w, "<div class=\"findings-title\">Risk Findings</div>\n")
		for _, finding := range result.Findings {
			fc := "f-" + severityToClass(finding.Severity)
			f(w, "<div class=\"finding-item %s\">\n", fc)
			f(w, "<span class=\"sev-badge %s\">%s</span>\n",
				severityToClass(finding.Severity), html.EscapeString(finding.Severity))
			f(w, "<div class=\"finding-desc\">%s</div>\n", html.EscapeString(finding.Description))
			if finding.SourceURL != "" {
				f(w, "<div class=\"finding-extra\">Source: <a href=\"%s\" target=\"_blank\" rel=\"noopener\">%s</a></div>\n",
					html.EscapeString(finding.SourceURL), html.EscapeString(finding.SourceURL))
			}
			if finding.Evidence != "" && r.config.Verbose {
				f(w, "<div class=\"finding-extra\">Evidence: %s</div>\n", html.EscapeString(finding.Evidence))
			}
			if finding.Methodology != "" && r.config.Verbose {
				f(w, "<div class=\"finding-extra\">Method: %s</div>\n", html.EscapeString(finding.Methodology))
			}
			f(w, "</div>\n")
		}
	}

	f(w, "</div>\n") // pkg-body
	f(w, "</div>\n") // pkg-card
}

func severityToClass(severity string) string {
	switch severity {
	case "CRITICAL":
		return "critical"
	case "HIGH":
		return "high"
	case "MEDIUM":
		return "medium"
	case "LOW":
		return "low"
	default:
		return "low"
	}
}

func (r *Reporter) printHTMLScript(w io.Writer) {
	f(w, `<script>
function toggle(slug){var c=document.getElementById('pkg-'+slug);if(c)c.classList.toggle('open')}
function showPkg(slug){var c=document.getElementById('pkg-'+slug);if(c)c.classList.add('open')}
</script>
`)
}
