package analyzer

import (
	"sync"
	"time"

	"github.com/metalstormbass/snyft/pkg/models"
)

// RepoAnalysisData holds the results of repo-level analysis that can be shared
// across all packages originating from the same source repository. This avoids
// redundant cloning, API calls, and analysis for repos like aws-sdk-java where
// 100+ artifacts all point to the same GitHub repository.
//
// Justification: Large dependency lists (e.g. 7,749 Maven artifacts) often map
// to far fewer unique repositories (~400). Repo-level checks (governance, CI,
// health, provenance) are identical for all artifacts from the same repo.
//
// Source: "Small World with High Risks" (Zimmermann et al., 2019) — dependency
// networks exhibit high duplication at the repository level.
type RepoAnalysisData struct {
	// Repository metadata (from analyzeRepository)
	SourceCodeAvailable bool
	RepoOwner           string
	RepoName            string
	RepoStars           int
	RepoForks           int
	RepoWatchers        int
	RepoOpenIssues      int
	RepoLastCommit      time.Time
	RepoCreatedAt       time.Time
	RepoUpdatedAt       time.Time
	RepoDefaultBranch   string
	RepoArchived        bool

	// Build infrastructure (from analyzeBuildInfrastructure)
	BuildInfrastructure string
	HasCI               bool
	CISystems           []string
	BuildSystems        []models.BuildSystemInfo
	HasSelfHosted       bool
	CIWorkflowRisks     []models.CIWorkflowRisk
	HasReleaseProcess   bool

	// Health metrics (from analyzeHealthMetrics)
	BusFactor              int
	CommitDistribution     map[string]int
	TopContributorPct      float64
	CodeReviewRate         float64
	RequiredReviewers      int
	HasBranchProtection    bool
	BranchProtectionDenied bool
	CIQualityScore         int

	// Provenance (repo-level parts from analyzeProvenance)
	SignedReleases    bool
	TotalReleaseCount int

	// Release documentation (from analyzeReleaseDocumentation)
	ReleaseDocumentation *models.ReleaseDocumentation

	// OSSF Scorecard (from analyzeOSSFScorecard)
	OSSFScore  float64
	OSSFChecks map[string]int

	// Scorecard URL
	ScorecardURL string

	// Findings and risk factors generated by repo-level analysis.
	// These are copied into each package's result.
	Findings    []models.Finding
	RiskFactors []string
}

// repoAnalysisCache provides thread-safe caching of repo-level analysis results.
// It uses a singleflight-like pattern: if repo A is being analyzed and another
// goroutine requests the same repo, it waits for the first analysis to complete
// rather than starting a duplicate analysis.
type repoAnalysisCache struct {
	mu       sync.Mutex
	data     map[string]*RepoAnalysisData
	inflight map[string]chan struct{}
}

func newRepoAnalysisCache() *repoAnalysisCache {
	return &repoAnalysisCache{
		data:     make(map[string]*RepoAnalysisData),
		inflight: make(map[string]chan struct{}),
	}
}

// getOrWait checks if repo-level analysis data is available for the given key.
// Returns (data, true) if cached or after waiting for an inflight analysis.
// Returns (nil, false) if the caller should perform the analysis. In this case,
// the caller MUST call set() when done to unblock any waiters.
func (c *repoAnalysisCache) getOrWait(key string) (*RepoAnalysisData, bool) {
	c.mu.Lock()

	// Check if already cached
	if data, ok := c.data[key]; ok {
		c.mu.Unlock()
		return data, true
	}

	// Check if another goroutine is already analyzing this repo
	if ch, ok := c.inflight[key]; ok {
		c.mu.Unlock()
		<-ch // wait for the inflight analysis to complete
		c.mu.Lock()
		data := c.data[key]
		c.mu.Unlock()
		return data, data != nil
	}

	// No cache hit and no inflight analysis — register as inflight
	ch := make(chan struct{})
	c.inflight[key] = ch
	c.mu.Unlock()
	return nil, false
}

// set stores repo-level analysis data and notifies any waiting goroutines.
func (c *repoAnalysisCache) set(key string, data *RepoAnalysisData) {
	c.mu.Lock()
	c.data[key] = data
	if ch, ok := c.inflight[key]; ok {
		close(ch) // notify waiters
		delete(c.inflight, key)
	}
	c.mu.Unlock()
}

// Len returns the number of cached repo analyses.
func (c *repoAnalysisCache) Len() int {
	c.mu.Lock()
	defer c.mu.Unlock()
	return len(c.data)
}

// applyRepoData copies cached repo-level analysis data into a per-package result.
func applyRepoData(result *models.AnalysisResult, rd *RepoAnalysisData) {
	result.SourceCodeAvailable = rd.SourceCodeAvailable
	result.BuildInfrastructure = rd.BuildInfrastructure
	result.ScorecardURL = rd.ScorecardURL

	// Repository metadata
	result.Metadata.RepoOwner = rd.RepoOwner
	result.Metadata.RepoName = rd.RepoName
	result.Metadata.RepoStars = rd.RepoStars
	result.Metadata.RepoForks = rd.RepoForks
	result.Metadata.RepoWatchers = rd.RepoWatchers
	result.Metadata.RepoOpenIssues = rd.RepoOpenIssues
	result.Metadata.RepoLastCommit = rd.RepoLastCommit
	result.Metadata.RepoCreatedAt = rd.RepoCreatedAt
	result.Metadata.RepoUpdatedAt = rd.RepoUpdatedAt
	result.Metadata.RepoDefaultBranch = rd.RepoDefaultBranch
	result.Metadata.RepoArchived = rd.RepoArchived

	// Build infrastructure
	result.Metadata.HasCI = rd.HasCI
	result.Metadata.CISystems = rd.CISystems
	result.Metadata.BuildSystems = rd.BuildSystems
	result.Metadata.HasSelfHosted = rd.HasSelfHosted
	result.Metadata.CIWorkflowRisks = rd.CIWorkflowRisks
	result.Metadata.HasReleaseProcess = rd.HasReleaseProcess

	// Health metrics
	result.Metadata.BusFactor = rd.BusFactor
	result.Metadata.CommitDistribution = rd.CommitDistribution
	result.Metadata.TopContributorPct = rd.TopContributorPct
	result.Metadata.CodeReviewRate = rd.CodeReviewRate
	result.Metadata.RequiredReviewers = rd.RequiredReviewers
	result.Metadata.HasBranchProtection = rd.HasBranchProtection
	result.Metadata.BranchProtectionDenied = rd.BranchProtectionDenied
	result.Metadata.CIQualityScore = rd.CIQualityScore

	// Provenance (repo-level)
	result.Metadata.SignedReleases = rd.SignedReleases
	result.Metadata.TotalReleaseCount = rd.TotalReleaseCount

	// Release documentation
	result.Metadata.ReleaseDocumentation = rd.ReleaseDocumentation

	// OSSF Scorecard
	result.Metadata.OSSFScore = rd.OSSFScore
	result.Metadata.OSSFChecks = rd.OSSFChecks

	// Copy findings and risk factors (make copies to avoid shared slice mutation)
	result.Findings = append(result.Findings, rd.Findings...)
	result.RiskFactors = append(result.RiskFactors, rd.RiskFactors...)
}

// extractRepoData builds a RepoAnalysisData from a completed analysis result.
// This is called after the first package from a repo completes repo-level analysis,
// to cache the data for subsequent packages from the same repo.
func extractRepoData(result *models.AnalysisResult) *RepoAnalysisData {
	rd := &RepoAnalysisData{
		SourceCodeAvailable: result.SourceCodeAvailable,
		ScorecardURL:        result.ScorecardURL,

		// Repository metadata
		RepoOwner:         result.Metadata.RepoOwner,
		RepoName:          result.Metadata.RepoName,
		RepoStars:         result.Metadata.RepoStars,
		RepoForks:         result.Metadata.RepoForks,
		RepoWatchers:      result.Metadata.RepoWatchers,
		RepoOpenIssues:    result.Metadata.RepoOpenIssues,
		RepoLastCommit:    result.Metadata.RepoLastCommit,
		RepoCreatedAt:     result.Metadata.RepoCreatedAt,
		RepoUpdatedAt:     result.Metadata.RepoUpdatedAt,
		RepoDefaultBranch: result.Metadata.RepoDefaultBranch,
		RepoArchived:      result.Metadata.RepoArchived,

		// Build infrastructure
		BuildInfrastructure: result.BuildInfrastructure,
		HasCI:               result.Metadata.HasCI,
		CISystems:           result.Metadata.CISystems,
		BuildSystems:        result.Metadata.BuildSystems,
		HasSelfHosted:       result.Metadata.HasSelfHosted,
		CIWorkflowRisks:     result.Metadata.CIWorkflowRisks,
		HasReleaseProcess:   result.Metadata.HasReleaseProcess,

		// Health metrics
		BusFactor:              result.Metadata.BusFactor,
		CommitDistribution:     result.Metadata.CommitDistribution,
		TopContributorPct:      result.Metadata.TopContributorPct,
		CodeReviewRate:         result.Metadata.CodeReviewRate,
		RequiredReviewers:      result.Metadata.RequiredReviewers,
		HasBranchProtection:    result.Metadata.HasBranchProtection,
		BranchProtectionDenied: result.Metadata.BranchProtectionDenied,
		CIQualityScore:         result.Metadata.CIQualityScore,

		// Provenance (repo-level)
		SignedReleases:    result.Metadata.SignedReleases,
		TotalReleaseCount: result.Metadata.TotalReleaseCount,

		// Release documentation
		ReleaseDocumentation: result.Metadata.ReleaseDocumentation,

		// OSSF Scorecard
		OSSFScore:  result.Metadata.OSSFScore,
		OSSFChecks: result.Metadata.OSSFChecks,
	}

	// Copy findings and risk factors that are repo-level (not per-package).
	// We identify repo-level findings by their categories.
	repoLevelCategories := map[string]bool{
		"Repository Access":                true,
		"Archived Repository":              true,
		"Stale Repository":                 true,
		"Low Community Engagement":         true,
		"CI Script Injection":              true,
		"Dangerous CI Triggers":            true,
		"Excessive CI Permissions":         true,
		"Unpinned CI Dependencies":         true,
		"Missing CI Environment Protection": true,
		"Self-Hosted CI Runners":           true,
		"No CI/CD":                         true,
		"Manual Releases":                  true,
		"Low OSSF Score":                   true,
	}

	for _, f := range result.Findings {
		if repoLevelCategories[f.Category] {
			rd.Findings = append(rd.Findings, f)
		}
	}

	repoLevelRiskFactors := map[string]bool{
		"Archived repository":                                     true,
		"Inactive development":                                    true,
		"Limited community adoption":                              true,
		"CI workflow vulnerable to script injection":               true,
		"CI workflow uses dangerous triggers":                      true,
		"Self-hosted build runners (uncontrolled build environment)": true,
		"No automated build verification":                         true,
		"Low supply chain security score":                         true,
	}

	for _, rf := range result.RiskFactors {
		if repoLevelRiskFactors[rf] {
			rd.RiskFactors = append(rd.RiskFactors, rf)
		}
	}

	return rd
}
